# Generated by Django 6.0.6 on 2026-06-20 10:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IndustryTrend',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('industry', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('trend_data', models.JSONField(default=dict)),
                ('source', models.CharField(blank=True, max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'industry_trends',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SalaryInsight',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(max_length=200)),
                ('industry', models.CharField(max_length=100)),
                ('experience_level', models.CharField(max_length=50)),
                ('salary_range', models.CharField(max_length=100)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('source', models.CharField(blank=True, max_length=500)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'salary_insights',
                'ordering': ['role'],
            },
        ),
        migrations.CreateModel(
            name='SkillAssessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=100)),
                ('skills_evaluated', models.JSONField(default=list)),
                ('questions', models.JSONField(default=list)),
                ('answers', models.JSONField(blank=True, default=dict)),
                ('scores', models.JSONField(blank=True, default=dict)),
                ('overall_score', models.FloatField(default=0.0)),
                ('recommendations', models.JSONField(blank=True, default=list)),
                ('time_taken_minutes', models.IntegerField(default=0)),
                ('is_completed', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_assessments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'skill_assessments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CareerRecommendation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('career_options', models.JSONField(default=list)),
                ('skill_gaps', models.JSONField(default=list)),
                ('suggested_courses', models.JSONField(default=list)),
                ('industry_insights', models.JSONField(default=dict)),
                ('salary_insights', models.JSONField(default=dict)),
                ('career_path', models.JSONField(default=list)),
                ('internship_recommendations', models.JSONField(default=list)),
                ('project_recommendations', models.JSONField(default=list)),
                ('summary', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='career_recommendations', to=settings.AUTH_USER_MODEL)),
                ('assessment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='career.skillassessment')),
            ],
            options={
                'db_table': 'career_recommendations',
                'ordering': ['-created_at'],
            },
        ),
    ]
