# Generated by Django 6.0.6 on 2026-06-20 10:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Roadmap',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('career_goal', models.CharField(choices=[('web_development', 'Web Development'), ('ai_ml', 'AI/ML'), ('data_science', 'Data Science'), ('cybersecurity', 'Cybersecurity'), ('devops', 'DevOps'), ('mobile_development', 'Mobile Development'), ('cloud_computing', 'Cloud Computing'), ('blockchain', 'Blockchain'), ('other', 'Other')], max_length=50)),
                ('custom_goal', models.CharField(blank=True, max_length=200)),
                ('duration_months', models.IntegerField(default=6)),
                ('milestones', models.JSONField(default=list)),
                ('resources', models.JSONField(blank=True, default=list)),
                ('progress', models.FloatField(default=0.0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roadmaps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'roadmaps',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('url', models.URLField(blank=True)),
                ('resource_type', models.CharField(choices=[('course', 'Course'), ('video', 'Video'), ('article', 'Article'), ('book', 'Book'), ('documentation', 'Documentation'), ('tool', 'Tool'), ('project', 'Project'), ('other', 'Other')], max_length=20)),
                ('is_free', models.BooleanField(default=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('roadmap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_set', to='roadmaps.roadmap')),
            ],
            options={
                'db_table': 'resources',
            },
        ),
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('order', models.IntegerField(default=0)),
                ('resources', models.JSONField(blank=True, default=list)),
                ('duration_days', models.IntegerField(default=7)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('skipped', 'Skipped')], default='pending', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('roadmap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestone_set', to='roadmaps.roadmap')),
            ],
            options={
                'db_table': 'milestones',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='DailyPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('tasks', models.JSONField(default=list)),
                ('notes', models.TextField(blank=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('milestone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_plans', to='roadmaps.milestone')),
            ],
            options={
                'db_table': 'daily_plans',
                'ordering': ['date'],
                'unique_together': {('milestone', 'date')},
            },
        ),
    ]
