# Generated by Django 6.0.6 on 2026-06-20 10:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('content', models.TextField()),
                ('excerpt', models.TextField(blank=True)),
                ('keywords', models.JSONField(blank=True, default=list)),
                ('seo_title', models.CharField(blank=True, max_length=500)),
                ('seo_description', models.TextField(blank=True)),
                ('seo_tags', models.JSONField(blank=True, default=list)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='blog_covers/')),
                ('reading_time', models.IntegerField(default=0)),
                ('word_count', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('is_generated', models.BooleanField(default=False)),
                ('grammar_checked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blogs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'blogs',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='BlogVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('content', models.TextField()),
                ('version_number', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='blogs.blog')),
            ],
            options={
                'db_table': 'blog_versions',
                'ordering': ['-version_number'],
            },
        ),
        migrations.CreateModel(
            name='SEOSuggestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('suggestion_type', models.CharField(max_length=50)),
                ('current_value', models.TextField(blank=True)),
                ('suggested_value', models.TextField()),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seo_suggestions', to='blogs.blog')),
            ],
            options={
                'db_table': 'seo_suggestions',
            },
        ),
    ]
