# Generated by Django 6.0.6 on 2026-06-20 10:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoSummary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('url', models.URLField(max_length=2000)),
                ('video_id', models.CharField(max_length=100)),
                ('channel_name', models.CharField(blank=True, max_length=255)),
                ('duration', models.IntegerField(default=0)),
                ('thumbnail_url', models.URLField(blank=True, max_length=2000)),
                ('transcript', models.TextField(blank=True)),
                ('summary', models.TextField()),
                ('key_points', models.JSONField(default=list)),
                ('notes', models.TextField(blank=True)),
                ('quiz', models.JSONField(blank=True, default=list)),
                ('language', models.CharField(default='en', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_summaries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'video_summaries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SavedNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('video_summary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_notes', to='youtube.videosummary')),
            ],
            options={
                'db_table': 'video_saved_notes',
            },
        ),
    ]
