# Generated by Django 6.0.6 on 2026-06-20 10:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PDFChatSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdf_chat_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pdf_chat_sessions',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='PDFChatMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], max_length=20)),
                ('content', models.TextField()),
                ('relevant_sections', models.JSONField(blank=True, default=list)),
                ('page_references', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='pdfchat.pdfchatsession')),
            ],
            options={
                'db_table': 'pdf_chat_messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='PDFDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='pdfs/')),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('file_size', models.IntegerField(default=0)),
                ('page_count', models.IntegerField(default=0)),
                ('content_text', models.TextField(blank=True)),
                ('is_processed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdf_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pdf_documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='pdfchatsession',
            name='pdf_documents',
            field=models.ManyToManyField(related_name='chat_sessions', to='pdfchat.pdfdocument'),
        ),
        migrations.CreateModel(
            name='DocumentHighlight',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('page_number', models.IntegerField(default=0)),
                ('color', models.CharField(default='yellow', max_length=20)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdf_highlights', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highlights', to='pdfchat.pdfdocument')),
            ],
            options={
                'db_table': 'document_highlights',
            },
        ),
    ]
